apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fibonacci-api
  name: fibonacci-api-deployment
spec:
  template:
    spec:
      containers:
      - name: fibonacci-api
      containers:
      - name: fibonacci-api
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
