apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-api-deployment
  labels:
    app: fibonacci-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fibonacci-api
  template:
    metadata:
      labels:
        app: fibonacci-api
    spec:
      containers:
      - name: fibonacci-api
        image: nishikantpatil/fibonacci-api:latest
        ports:
        - containerPort: 8080